# Exemplary SPARQL-insert query over a set of information given prefixes.
PREFIX schema: <http://schema.org/>
PREFIX : <http://example.org/devos/>

# The idea: A webpage identifies a person with the specified attributes.
# For the prototype, we utilize the address as search key, as it is known during the run-time of the smart contract.
INSERT { <http://example.org/devos/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266> a schema:Person;
  schema:givenName "Ash" ;
  schema:lastName "Ketchum" ;
  schema:nationality "Japan" ;
  :address "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" ;
} WHERE {} ;