# Example Query for reading information inserted.
# The idea: Query a specific person (here '0') and fetch information about that person.
SELECT ?o ?p ?o 
WHERE { 
	<http://example.org/devos/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266> ?p ?o .
}
